### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [facelessloser/SJ4000_14500_battery_mod#1]
Hello!

I found link to this project from https://hackaday.com/2020/06/09/external-battery-mod-for-action-camera-does-it-non-destructively/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by facelesstech** [comment]
Hi thanks for bring this to my attention, I've added a GPLv3 license to this project.

**Comment by vazhnov** [comment]
@facelessloser, thank you for freedom license!
P.S.: branch https://github.com/facelessloser/SJ4000_14500_battery_mod/tree/add-license-1 is not merged into "master" yet…
